<?php

return [
    'enabled' => (bool) env('TEXTRACT_ENABLED', false),
    'source_disk' => env('TEXTRACT_SOURCE_DISK', 'textract'),
    'result_disk' => env('TEXTRACT_RESULT_DISK', 'local'),
    'region' => env('TEXTRACT_REGION', env('AWS_DEFAULT_REGION', 'us-east-1')),
    'bucket' => env('TEXTRACT_BUCKET', env('AWS_BUCKET')),
    'prefix' => trim((string) env('TEXTRACT_PREFIX', 'textract/input'), '/'),
    'result_prefix' => trim((string) env('TEXTRACT_RESULT_PREFIX', 'pdf-jobs'), '/'),
    'key' => env('TEXTRACT_KEY', env('AWS_ACCESS_KEY_ID')),
    'secret' => env('TEXTRACT_SECRET', env('AWS_SECRET_ACCESS_KEY')),
    'session_token' => env('TEXTRACT_SESSION_TOKEN', env('AWS_SESSION_TOKEN')),
    'endpoint' => env('TEXTRACT_ENDPOINT'),
    'use_path_style_endpoint' => (bool) env('TEXTRACT_USE_PATH_STYLE_ENDPOINT', env('AWS_USE_PATH_STYLE_ENDPOINT', false)),
    'use_sns' => (bool) env('TEXTRACT_USE_SNS', false),
    'sns_topic_arn' => env('TEXTRACT_SNS_TOPIC_ARN'),
    'sns_role_arn' => env('TEXTRACT_SNS_ROLE_ARN'),
    'poll_delay_seconds' => (int) env('TEXTRACT_POLL_DELAY_SECONDS', 10),
    'max_poll_attempts' => (int) env('TEXTRACT_MAX_POLL_ATTEMPTS', 120),
    'keep_source_in_s3' => (bool) env('TEXTRACT_KEEP_SOURCE_IN_S3', false),
    'delete_source_after_completion' => (bool) env('TEXTRACT_DELETE_SOURCE_AFTER_COMPLETION', true),
    'minimum_line_confidence' => (float) env('TEXTRACT_MINIMUM_LINE_CONFIDENCE', 0.0),
    'baseline_ratio' => (float) env('TEXTRACT_BASELINE_RATIO', env('PDF_LINE_OCR_BASELINE_RATIO', 0.82)),
    'force_for_scanned_documents' => (bool) env('TEXTRACT_FORCE_FOR_SCANNED_DOCUMENTS', false),
    'default_page_width_pt' => (float) env('TEXTRACT_DEFAULT_PAGE_WIDTH_PT', 612.0),
    'default_page_height_pt' => (float) env('TEXTRACT_DEFAULT_PAGE_HEIGHT_PT', 792.0),
    'memory_limit' => env('TEXTRACT_MEMORY_LIMIT', '512M'),
    'max_results' => max(1, min(1000, (int) env('TEXTRACT_MAX_RESULTS', 250))),
];
